# File to Database Loader Project
- reading a CSV file from directory
- validating and processig the data
- writing the data into a sql database
- handling the large file via Chunking

In [1]:
import pandas as pd
import zipfile

In [2]:
import os
zip_path = '/home/rohan/DataEngineering/Python_learning/Project-2-File-to-Database-Loader/Video+Game+Sales.zip'
print(os.path.exists(zip_path))  # Check if the zip file exists

True

In [3]:
with zipfile.ZipFile(zip_path,'r') as z:
    z.extractall('extracted_video_games_sales')

In [4]:
# imported raw data
raw_df= pd.read_csv('extracted_video_games_sales/vgchartz-2024.csv')

In [5]:
raw_df.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [6]:
raw_df.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='object')

In [7]:
raw_df = raw_df[['title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update']]

In [8]:
raw_df.head()

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [9]:
raw_df.rename(columns= {'title' : 'Game_title','console':'Console', 'genre': 'Genre','publisher':   'Publisher','developer':'Developer','critic_score':'Critic_Score','total_sales':'Total_Sales','na_sales': 'Namr_sales','jp_sales':'Japan_sales','pal_sales':'PAL_sales','other_sales':'Other_sales','release_date':'Release_date','last_update':'Last_update'}, inplace = True)

In [10]:
raw_df.head()

,Game_title,Console,Genre,Publisher,Developer,Critic_Score,Total_Sales,Namr_sales,Japan_sales,PAL_sales,Other_sales,Release_date,Last_update
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [11]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Game_title    64016 non-null  object
 1   Console       64016 non-null  object
 2   Genre         64016 non-null  object
 3   Publisher     64016 non-null  object
 4   Developer     63999 non-null  object
 5   Critic_Score  6678 non-null   float64
 6   Total_Sales   18922 non-null  float64
 7   Namr_sales    12637 non-null  float64
 8   Japan_sales   6726 non-null   float64
 9   PAL_sales     12824 non-null  float64
 10  Other_sales   15128 non-null  float64
 11  Release_date  56965 non-null  object
 12  Last_update   17879 non-null  object
dtypes: float64(6), object(7)
memory usage: 6.3+ MB

In [12]:
raw_df.isnull().sum()

Game_title          0
Console             0
Genre               0
Publisher           0
Developer          17
Critic_Score    57338
Total_Sales     45094
Namr_sales      51379
Japan_sales     57290
PAL_sales       51192
Other_sales     48888
Release_date     7051
Last_update     46137
dtype: int64

In [13]:
raw_df.duplicated().sum()

np.int64(18)

In [14]:
raw_df[raw_df['Total_Sales'] > 10].head()

,Game_title,Console,Genre,Publisher,Developer,Critic_Score,Total_Sales,Namr_sales,Japan_sales,PAL_sales,Other_sales,Release_date,Last_update
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [15]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Game_title    64016 non-null  object
 1   Console       64016 non-null  object
 2   Genre         64016 non-null  object
 3   Publisher     64016 non-null  object
 4   Developer     63999 non-null  object
 5   Critic_Score  6678 non-null   float64
 6   Total_Sales   18922 non-null  float64
 7   Namr_sales    12637 non-null  float64
 8   Japan_sales   6726 non-null   float64
 9   PAL_sales     12824 non-null  float64
 10  Other_sales   15128 non-null  float64
 11  Release_date  56965 non-null  object
 12  Last_update   17879 non-null  object
dtypes: float64(6), object(7)
memory usage: 6.3+ MB

In [16]:
## Clean the data
# remove all NULL - Int to NULL and string to NULL
# check for duplocate rows and delete
# standardizing data- All to lower case
# remove white spaces

raw_df

,Game_title,Console,Genre,Publisher,Developer,Critic_Score,Total_Sales,Namr_sales,Japan_sales,PAL_sales,Other_sales,Release_date,Last_update
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11,2019-01-28
64012,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64013,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64014,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28,2019-02-24
64015,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-29